#Lab 2 - Inferential Statistics

By the end of this practical you will be able to apply Inferential statistics methods using Python

Goto Gitbub to see the data files

https://github.com/chwee/AGO_L4_Statistic

## 1.  Case 1 

A physician is evaluating a new diet for her patients with a family history of heart disease. To test the effectiveness of this diet, 16 patients are placed on the diet for 6 months. Their weights and triglyceride levels are measured before and after the study, and the physician wants to know if either set of measurements has changed. (Data set: dietstudy.csv) 

*what type of hypothesis test to use?*


<details><summary>Click here for answer</summary> 
<br/>
Two Sample T-Test (Paired)
<br/>
</details>
<br/>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
%matplotlib inline

###Read the dataset 


<details><summary>Click here for answer</summary> 
<br/>

The data file is stored at the github

https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dietstudy.csv

```
diet = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dietstudy.csv')
diet.head()
```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [2]:

diet = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dietstudy.csv')

diet.head()

   patid  age  gender  tg0  tg1  tg2  tg3  tg4  wgt0  wgt1  wgt2  wgt3  wgt4
0      1   45    Male  180  148  106  113  100   198   196   193   188   192
1      2   56    Male  139   94  119   75   92   237   233   232   228   225
2      3   50    Male  152  185   86  149  118   233   231   229   228   226
3      4   46  Female  112  145  136  149   82   179   181   177   174   172
4      5   64    Male  156  104  157   79   97   219   217   215   213   214

Check dataset size

<details><summary>Click here for answer</summary> 
<br/>

```
diet.shape
```

<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
diet.shape

(16, 13)

### Identify Test Statistic

Find the mean for the triglyceride and Weights before and after the diet.

<details><summary>Click here for answer</summary> 
<br/>

Two Sample T-Test (Paired)

```
print("The triglyceride levels of patients were {}".format(diet.tg0.mean()))
print("The final triglyceride levels of patients are {}".format(diet.tg4.mean()))
print("The weights of pateints were {}".format(diet.wgt0.mean()))
print("The final weights of pateints are {}".format(diet.wgt4.mean()))
```


    
<br/>
</details>

<br/>

<details><summary>Click here for answer</summary> 
<br/>

<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
print("The triglyceride levels of patients were {}".format(diet.tg0.mean()))
print("The final triglyceride levels of patients are {}".format(diet.tg4.mean()))
print("The weights of pateints were {}".format(diet.wgt0.mean()))
print("The final weights of pateints are {}".format(diet.wgt4.mean()))

The triglyceride levels of patients were 138.4375
The final triglyceride levels of patients are 124.375
The weights of pateints were 198.375
The final weights of pateints are 190.3125

#### Triglycerides

H0:  levels of Triglycerides of individual before diet == levels of Triglycerides of individual after diet 

H1:  levels of Triglycerides of individual before diet != levels of Triglycerides of individual after diet 

Use:<br>
import scipy.stats as stats <br>
stats.ttest_rel() <br>
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_rel.html<br>

<details><summary>Click here for answer</summary> 
<br/>


```
stage1_trig = stats.ttest_rel(a=diet.tg0,b=diet.tg4) 

#a =triglyceride levels before diet
#b = triglyceride levels after diet)
```

Get the pvalue

```
stage1_trig.pvalue
```

Check pvalue with confidence level 0.025


```
stage1_trig.pvalue>0.025
```


    
<br/>
</details>

<br/>

In [ ]:
#Add code
#T test

In [ ]:
#Add code
#get p-value

In [ ]:
#Add code
#check significant -check p-value with alpha

In [ ]:
stage1_trig = stats.ttest_rel(a=diet.tg0,b=diet.tg4) 

#a =triglyceride levels before diet
#b = triglyceride levels after diet)

In [ ]:
stage1_trig.pvalue

0.24874946576903698

In [ ]:
stage1_trig.pvalue<0.05

False

#### Weights

#### H0:  weights of individual before diet == weights of individual after diet 

#### H1:  weights of individual before diet != weights of individual after diet



<details><summary>Click here for answer</summary> 
<br/>

```
stage2_weight = stats.ttest_rel(a=diet.wgt0,b=diet.wgt4) 

#a = weights before diet
#b = weights after diet
```

Get pvalue

```
stage2_weight.pvalue
```

Check pvalue with confidence level 0.025


```
stage2_weight.pvalue>0.025
```

<br/>
</details>

<br/>

In [ ]:
#Add code
#T test

In [ ]:
#Add code
#get p-value

In [ ]:
#Add code
#check significant -check p-value with alpha

In [ ]:
stage2_weight = stats.ttest_rel(a=diet.wgt0,b=diet.wgt4) 

#a = weights before diet
#b = weights after diet

In [ ]:
stage2_weight.pvalue

1.137689414996614e-08

In [ ]:
stage2_weight.pvalue<0.05

True

### Conclusions


<details><summary>Click here for answer</summary> 
<br/>


1.   However, the p-value greater than 0.05 for change in triglyceride level shows the diet did not significantly reduce their triglyceride levels. Accept Null Hypothesis
2.   Since the p-value for change in weight is less than 0.05,we can conclude that the average loss of 8.06 pounds per patient is not due to chance variation, and can be attributed to the diet. Reject Null Hypothesis


<br/>
</details>

<br/>

## 2. Case 2
An analyst at a department store wants to evaluate a recent credit card promotion. To this end, 500 cardholders were randomly selected. Half received an ad promoting a reduced interest rate on purchases made over the next three months, and half received a standard seasonal ad. Is the promotion effective to increase sales? <br>
<br>
*what type of hypothesis test to use?*<br>

<details><summary>Click here for answer</summary> 
<br/>
Two Sample T-Test (Indepedent)
<br/>
</details>
<br/>

### Read dataset

<details><summary>Click here for answer</summary> 
<br/>

https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/creditpromo.csv

```
analyst_cre = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/creditpromo.csv')

analyst_cre.head()
```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [3]:
analyst_cre = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/creditpromo.csv')

analyst_cre.head()

     id         insert      dollars
0   148       Standard  2232.771979
1   572  New Promotion  1403.807542
2   973       Standard  2327.092181
3  1096       Standard  1280.030541
4  1541  New Promotion  1513.563200

### Get mean for Standard and New Promotion

<details><summary>Click here for answer</summary> 
<br/>

```

standard = analyst_cre['dollars'].loc[analyst_cre['insert']=="Standard"]

promotion = analyst_cre['dollars'].loc[analyst_cre['insert']=="New Promotion"]

print("The average spent by the normal ad is ${}".format(standard.mean()))

print("The average spent by the promotion ad is ${}".format(promotion.mean()))

```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
standard = analyst_cre['dollars'].loc[analyst_cre['insert']=="Standard"]

promotion = analyst_cre['dollars'].loc[analyst_cre['insert']=="New Promotion"]

In [ ]:
print("The average spent by the normal ad is ${}".format(standard.mean()))

print("The average spent by the promotion ad is ${}".format(promotion.mean()))

The average spent by the normal ad is $1566.389030965934
The average spent by the promotion ad is $1637.4999830648003

Observation<br>

<details><summary>Click here for answer</summary> 
<br/>
On average, customers who received the interest-rate promotion charged about $70 more than the normal standard season ad, and they vary a little more around their average
<br/>
</details>

<br/>

### Indentify test statistic




H0:  Promotion is not effective to increase sales

H1:  Promotion is  effective to increase sales
<br>
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html<br>

<br>


<details><summary>Click here for answer</summary> 
<br/>

2 sample T test independent

```
eq_var = stats.ttest_ind(a= standard,b= promotion)   

eq_var.pvalue

p = eq_var.pvalue

print(" For the above test, the p-value is {}".format(p))

if(p<0.025):
    print('We reject null hypothesis')
else:
    print('We accept null hypothesis')


```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
eq_var = stats.ttest_ind(a= standard,
                b= promotion)    # equal variance
eq_var.statistic
eq_var.pvalue

0.024225996894147395

In [ ]:

p = eq_var.pvalue

print(" For the above test, the p-value is {}".format(p))

if(p<0.05):
    print('We reject null hypothesis')
else:
    print('We accept null hypothesis')

 For the above test, the p-value is 0.024225996894147395
We reject null hypothesis

Conclusion<br>
<details><summary>Click here for answer</summary> 
<br/>
* Since the significance value of the test is less than 0.05, we can safely conclude that the average of 71.11 dollars more spent by cardholders receiving the reduced interest rate is not due to chance alone. The store will now consider extending the offer to all credit customers.
<br/>
</details>

<br/>

## 3. Execrise  Case 3
An experiment is conducted to study the hybrid seed production of bottle gourd under open field conditions. The main aim of the investigation is to compare natural pollination and hand pollination. The data are collected on 10 randomly selected plants from each of natural pollination and hand pollination. The data are collected on fruit weight (kg), seed yield/plant (g) and seedling length (cm). (Data set: pollination.csv)
<br>

### a. Is the overall population of Seed yield/plant (g) equals to 200?


<br>

*what type of hypothesis test to use?*<br>

<details><summary>Click here for answer</summary> 
<br/>
One Sample t-Test
<br/>
</details>
<br/>

<br>
<br>
Load dataset
<details><summary>Click here for answer</summary> 
<br/>

https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/pollination.csv

```
poll = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/pollination.csv')
poll.head()
```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [4]:
poll = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/pollination.csv')

poll.head()

     Group  Fruit_Wt  Seed_Yield_Plant  Seedling_length
0  Natural      1.85            147.70            16.86
1  Natural      1.86            136.86            16.77
2  Natural      1.83            149.97            16.35
3  Natural      1.89            172.33            18.26
4  Natural      1.80            144.46            17.90

Find the mean for Seed yield/plant
<br>
<details><summary>Click here for answer</summary> 
<br/>

```

poll.Seed_Yield_Plant.mean()


```
<br/>
</details>

In [ ]:
#Add code

In [ ]:
poll.Seed_Yield_Plant.mean()

180.8035

One sample T Test


H0:  Overall population mean of seed yield plant equal to 200 

H1:  Overall population mean of seed yield plant not equal to 200 



<br>
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_1samp.html<br>

<br>
<details><summary>Click here for answer</summary> 
<br/>

```

ttest_1 = stats.ttest_1samp(a=poll.Seed_Yield_Plant,popmean = 200)

p_value = ttest_1.pvalue

print("The p value is }".format(p_value))

if(p<0.025):
    print('We reject null hypothesis')
else:
    print('We accept null hypothesis')

```
<br/>
</details>

In [ ]:
#Add code

In [ ]:
ttest_1 = stats.ttest_1samp(a=poll.Seed_Yield_Plant, popmean = 200)

p_value = ttest_1.pvalue
print("The p value is {} ".format(p_value))

The p value is 0.032891040921283025

In [ ]:
p_value<0.05

True

In [ ]:
ttest_1 = stats.ttest_1samp(a=poll.Seed_Yield_Plant, popmean = 200,alternative='greater')

p_value = ttest_1.pvalue
print("The p value is {} ".format(p_value))

The p value is 0.9835544795393585

Conclusion

<br>
<details><summary>Click here for answer</summary> 
<br/>

* Since the significance value of the test is less than 0.05, we reject the null hypothesis. Therefore overall population of seed yield/plant is  not equal to 200.
<br/>
</details>

### b. Test whether the natural pollination and hand pollination under open field conditions are equally effective or are significantly different.

<br>

*what type of hypothesis test to use?*<br>


<details><summary>Click here for answer</summary> 
<br/>
2 sample t-test independent

<br/>
</details>




<details><summary>Click here for answer</summary> 
<br/>

H0  : mean Fruit_Wt(Natural) == mean Fruit_Wt(Hand)

H1  : mean Fruit_Wt(Natural) != mean Fruit_Wt(Hand)

Extract data for Natural and Hand pollination

```
natural_fruit_wt = poll['Fruit_Wt'].loc[poll['Group']=="Natural"]
hand_fruit_wt = poll['Fruit_Wt'].loc[poll['Group']=="Hand"]

natural_seed_yield = poll['Seed_Yield_Plant'].loc[poll['Group']=="Natural"]
hand_seed_yield = poll['Seed_Yield_Plant'].loc[poll['Group']=="Hand"]

natural_seedling_length = poll['Seedling_length'].loc[poll['Group']=="Natural"]
hand_seedling_length = poll['Seedling_length'].loc[poll['Group']=="Hand"]
```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
natural_fruit_wt = poll['Fruit_Wt'].loc[poll['Group']=="Natural"]
hand_fruit_wt = poll['Fruit_Wt'].loc[poll['Group']=="Hand"]


Do sample test
<details><summary>Click here for answer</summary> 
<br/>

```


# Perfrom 2 sample t test independent
eq_var = stats.ttest_ind(a= natural_fruit_wt ,
                b= hand_fruit_wt )    # equal variance
eq_var.statistic
eq_var.pvalue
```



<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
eq_var = stats.ttest_ind(a= natural_fruit_wt ,
                b= hand_fruit_wt )    # equal variance
f1=eq_var.statistic
p1=eq_var.pvalue
print("The t-value is {} and the p value is {}".format(f1,p1))
print(p1<0.05)

The t-value is -17.669989614440286 and the p value is 8.078362076486221e-13
True

Conclusion

<br>
<details><summary>Click here for answer</summary> 
<br/>

* Since the all the test p-value is less than 0.05, we reject the null hypothesis. Therefore they are significant different in natural pollination and hand pollination .
<br/>
</details>

## 4. Case 4
An electronics firm is developing a new DVD player in response to customer requests. Using a prototype, the marketing team has collected focus data for different age groups viz. Under 25; 25-34; 35-44; 45-54; 55-64; 65 and above. Do you think that consumers of various ages rated the design differently? (Data set: dvdplayer.csv)<br>
<br>
*what type of hypothesis test to use?*<br>


<details><summary>Click here for answer</summary> 
<br/>
F-Test/Anova
<br/>
</details>
<br/>

###Load dataset 

<details><summary>Click here for answer</summary> 
<br/>

https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dvdplayer.csv

```

dvd = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dvdplayer.csv')

dvd.head()

```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [5]:
dvd = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/dvdplayer.csv')

dvd.head()

      agegroup   dvdscore
0  65 and over  38.454803
1        55-64  17.669677
2  65 and over  31.704307
3  65 and over  25.924460
4     Under 25  30.450007

### Identify Test Statistic

H0  : mean  (age_group_1(65 and over)) == mean(age_group_2(55-64)) == mean(age_group3(Under 25)) == mean(age_group4(35-54)) == mean(age_group5(45-54)) == mean(age_group_6(25-34))
                       (Consumers of various age groups rated the design similarly)
                       
 Ha  : mean(age_group_1(65 and over)) != mean(age_group_2(55-64)) != mean(age_group3(Under 25))!= mean(age_group4(35-54)) != mean(age_group5(45-54)) != mean(age_group_6(25-34))
                         
(Consumers of various age groups rated the design differently)


<br>
Extract data for each group 

<details><summary>Click here for answer</summary> 
<br/>

F-Test/Anova

```

age_group_1 = dvd['dvdscore'].loc[dvd['agegroup']=="65 and over"]
age_group_2 = dvd['dvdscore'].loc[dvd['agegroup']=="55-64"]
age_group_3 = dvd['dvdscore'].loc[dvd['agegroup']=="Under 25"]
age_group_4 = dvd['dvdscore'].loc[dvd['agegroup']=="35-44"]
age_group_5 = dvd['dvdscore'].loc[dvd['agegroup']=="45-54"]
age_group_6 = dvd['dvdscore'].loc[dvd['agegroup']=="25-34"]

```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
age_group_1 = dvd['dvdscore'].loc[dvd['agegroup']=="65 and over"]
age_group_2 = dvd['dvdscore'].loc[dvd['agegroup']=="55-64"]
age_group_3 = dvd['dvdscore'].loc[dvd['agegroup']=="Under 25"]
age_group_4 = dvd['dvdscore'].loc[dvd['agegroup']=="35-44"]
age_group_5 = dvd['dvdscore'].loc[dvd['agegroup']=="45-54"]
age_group_6 = dvd['dvdscore'].loc[dvd['agegroup']=="25-34"]

Do F-Test/Anova
<br>
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.f_oneway.html<br>
<br>

<details><summary>Click here for answer</summary> 
<br/>


```

# Perfrom the Anova
anova = stats.f_oneway(age_group_1,age_group_2,age_group_3,age_group_4,age_group_5,age_group_6)
# Statistic :  F Value
p = anova.pvalue
print("The p value is {}".format(p))
if(p<0.025):
    print('We reject null hypothesis')
else:
    print('We fail to reject null hypothesis')

```

<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
# Perfrom the Anova
anova = stats.f_oneway(age_group_1,age_group_2,age_group_3,age_group_4,age_group_5,age_group_6)
# Statistic :  F Value

p = anova.pvalue
print("The  p value is {}".format(p))
if(p<0.05):
    print('We reject null hypothesis')
else:
    print('We fail to reject null hypothesis')

The  p value is 3.087324905679639e-05
We reject null hypothesis

Conclusion<br>

<details><summary>Click here for answer</summary> 
<br/>
* Since the significance value of the test is less than 0.05, we reject the null hypothesis. Therefore,consumers of various ages rated the design differently
<br/>
</details>

<br/>

##5. Case 5
A doctor is evaluating a new medicine for her patients with a high blood pressure. To test the effectiveness of this medicine,the blood pressure before the medicine and after medicine are recorded.
<br>
*what type of hypothesis test to use?*<br>


<details><summary>Click here for answer</summary> 
<br/>
Z Test
<br/>
</details>
<br/>

###Load dataset
load the blood_pressure.csv


<details><summary>Click here for answer</summary> 
<br/>

https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/blood_pressure.csv

```

df = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/blood_pressure.csv')
df.head()

```

<br/>
</details>

<br/>

In [ ]:
#Add code

In [6]:
df = pd.read_csv('https://raw.githubusercontent.com/chwee/AGO_L4_Statistic/main/data/blood_pressure.csv')
df.head()

   patient   sex agegrp  bp_before  bp_after
0        1  Male  30-45        143       153
1        2  Male  30-45        163       170
2        3  Male  30-45        153       168
3        4  Male  30-45        153       142
4        5  Male  30-45        146       141

###Check the basic statistics for the data

<details><summary>Click here for answer</summary> 
<br/>

```

print(df[['bp_before','bp_after']].describe())

```
<br/>
</details>

<br/>

In [ ]:
#Add code

In [ ]:
print(df[['bp_before','bp_after']].describe())

        bp_before    bp_after
count  120.000000  120.000000
mean   156.450000  151.358333
std     11.389845   14.177622
min    138.000000  125.000000
25%    147.000000  140.750000
50%    154.500000  149.500000
75%    164.000000  161.000000
max    185.000000  185.000000

###Z Test
Since sample size is large use the Z Test

H0 : bp_before == bp_after

H1 : bp_before != bp_after
<br>
https://www.statsmodels.org/stable/generated/statsmodels.stats.weightstats.ztest.html<br>

<details><summary>Click here for answer</summary> 
<br/>

```

ztest ,pval1 = stests.ztest(df['bp_before'], x2=df['bp_after'], value=0,alternative='two-sided')

print(float(pval1))

if(pval1<0.05):

    print('We reject null hypothesis')

else:

    print('We fail to reject null hypothesis')


```

<br/>
</details>

<br/>

In [ ]:
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests
#Add code

In [ ]:
#Add code

In [ ]:
import pandas as pd
from scipy import stats
from statsmodels.stats import weightstats as stests
ztest ,pval1 = stests.ztest(df['bp_before'], x2=df['bp_after'])
print(float(pval1))

if(pval1<0.05):
    print('We reject null hypothesis')
else:
    print('We fail to reject null hypothesis')

0.002162306611369422
We reject null hypothesis




bp_before mean is not equal bp_after mean